### ISSUE TITLE
No CMakeList in project?

### ISSUE THREAD

**Issue by walzert** [iotbzh/txc-demo#3]
Hello I tried to build the app, after changing some versions (bower, gulp-sass) I followed in README.md the Build. But "cmake .." is not working because there is no Cmakelist in the root folder.
Did I something wrong or something didn't worked with npm install?

**Comment by pmarzin** [comment]
Hi!
Indeed, the readme file was deprecated. I just have updated the procedure and you should now be able to build the app and binding by following it.
Hope it helps.
Regards.

**Comment by jobol** [comment]
Thank you @pmarzin 

@walzert  can we close?

**Comment by walzert** [comment]
@pmarzin thank you for helping with that. 
@jobol you could close that issue. The  But there is now a error with cmake and the libmircohttpd.
The app was building with the parameter "npm audit fix --package-lock-only" and it seems to be fine. The binding has an error with libmicrohttpd.
I'm using Fedora 30 and have installed   libmicrohttpd-1:0.9.67-1.fc30.x86_64    and cmake version 3.13.2.
Should I use a other building machine? And open an other issue that you could close that one?                            
 


`  /home/walzert/Development/AGL/testapps/txc-demo/conf.d/cmake/bindings_config.cmake:196 (include)
  CMakeLists.txt:22 (include)


-- Configuring incomplete, errors occurred!
See also "/home/walzert/Development/AGL/testapps/txc-demo/build-binding/CMakeFiles/CMakeOutput.log".
(base) [walzert@inf-walzert-fed-fh-reutlingen-de build-binding]$ cmake ../binding
-- Distribution detected (separated by ';' choose one of them) fedora
-- Include: /home/walzert/Development/AGL/testapps/txc-demo/binding/../conf.d/app-templates/cmake/cmake.d/01-build_options.cmake
-- Checking for module 'libmicrohttpd>=0.9.55'
--   Package 'libmicrohttpd', required by 'virtual:world', not found
CMake Error at /usr/local/lib64/python3.7/site-packages/cmake/data/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/lib64/python3.7/site-packages/cmake/data/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  /home/walzert/Development/AGL/testapps/txc-demo/conf.d/app-templates/cmake/cmake.d/01-build_options.cmake:111 (PKG_CHECK_MODULES)
  /home/walzert/Development/AGL/testapps/txc-demo/conf.d/app-templates/cmake/common.cmake:85 (include)
  /home/walzert/Development/AGL/testapps/txc-demo/conf.d/cmake/bindings_config.cmake:196 (include)
  CMakeLists.txt:22 (include)
[CMakeOutput.log](https://github.com/iotbzh/txc-demo/files/3782480/CMakeOutput.log)

`

**Comment by jobol** [comment]
I think that you can fully remove the requirement to libmicrohttpd

Try and tell me if it works

**Comment by jobol** [comment]
in txc-demo/conf.d/app-templates/cmake/cmake.d/01-build_options.cmake line 111

**Comment by walzert** [comment]
@jobol  thank you that worked.
